spring:
  datasource:
    url: jdbc:h2:mem:db;MODE=PostgreSQL;
    username: root
    password: root
  h2:
    console:
      enabled: true
      path: /h2
  jpa:
    show-sql: true
    properties:
      hibernate:
        format_sql: true